Repository fluix/ffbt, pull requests merged in 2019-10, with the labels that each got.

#180 Fix no-boolean-literal-compare crash (by providing tsconfig.json)
  cli/commands/lint/ts.js
Labels: bug

#197 TS lint command
  src/cli/base-command.ts
  src/cli/commands/lint.ts
  src/paths.ts
  src/services/tslint/config.ts
  src/services/tslint/runner.ts
Labels: cli, linter

#200 Style lint command
  new-playground/src/bad-styles.scss
  package.json
  src/cli/commands/lint.ts
  src/services/stylelint/config.ts
  src/services/stylelint/runner.ts
  tsconfig.json
Labels: linter

#202 Typechecking disable option
  src/project-config/default.ts
  src/services/webpack/config/layers/typescript.ts
Labels: config

#201 Turn off/on notifications flag
  src/project-config/default.ts
  src/services/webpack/config/index.ts
Labels: config, core

#203 Travis ci
  .travis.yml
Labels: tests

#204 update dependencies
  package.json
Labels: dependencies

#206 rewrite readJson
  src/core/read-json.ts
Labels: core

#207 Create package lock file
  .npmrc
  package-lock.json
  package.json
Labels: dependencies
